[workspace]

members = [
    "cfg", "cfg-classify", "cfg-classify-useful", "cfg-symbol-bit-matrix", "cfg-earley", "cfg-generate", "cfg-predict", "cfg-predict-sets", "cfg-sequence",
    "cfg-symbol", "cfg-history", "cfg-classify-ll", "cfg-classify-lr", "cfg-classify-linear", "cfg-classify-cyclical", "cfg-classify-regular", "cfg-earley-history",
]

resolver = "2"
